apiVersion: apps/v1
kind: Deployment
metadata:
  name: dyno-code-deployment
  labels:
    app: dyno-code
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dyno-code
  template:
    metadata:
      labels:
        app: dyno-code
    spec:
      serviceAccountName: dyno-code-sa
      containers:
        - name: dyno-code
          image: gcr.io/pa2024-421814/dyno-code:latest
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_CLOUD_PROJECT_ID
              value: "pa2024-421814"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20